/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OpenapiDocsRouteImport } from './routes/openapi-docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as AuthLayoutVoiceClonesRouteImport } from './routes/_auth/_layout/voice-clones'
import { Route as AuthLayoutSpeakersRouteImport } from './routes/_auth/_layout/speakers'
import { Route as AuthLayoutMoreRouteImport } from './routes/_auth/_layout/more'
import { Route as AuthLayoutDashboardRouteImport } from './routes/_auth/_layout/dashboard'
import { Route as AuthLayoutAgentsRouteImport } from './routes/_auth/_layout/agents'
import { Route as AuthLayoutAgentsIndexRouteImport } from './routes/_auth/_layout/agents/index'
import { Route as AuthLayoutUserRolesRouteImport } from './routes/_auth/_layout/user/roles'
import { Route as AuthLayoutUserKnowledgeBasesRouteImport } from './routes/_auth/_layout/user/knowledge-bases'
import { Route as AuthLayoutUserDevicesRouteImport } from './routes/_auth/_layout/user/devices'
import { Route as AuthLayoutUserApiTokensRouteImport } from './routes/_auth/_layout/user/api-tokens'
import { Route as AuthLayoutAdminVisionConfigRouteImport } from './routes/_auth/_layout/admin/vision-config'
import { Route as AuthLayoutAdminVadConfigRouteImport } from './routes/_auth/_layout/admin/vad-config'
import { Route as AuthLayoutAdminUsersRouteImport } from './routes/_auth/_layout/admin/users'
import { Route as AuthLayoutAdminUdpConfigRouteImport } from './routes/_auth/_layout/admin/udp-config'
import { Route as AuthLayoutAdminTtsConfigRouteImport } from './routes/_auth/_layout/admin/tts-config'
import { Route as AuthLayoutAdminSpeakerConfigRouteImport } from './routes/_auth/_layout/admin/speaker-config'
import { Route as AuthLayoutAdminPoolStatsRouteImport } from './routes/_auth/_layout/admin/pool-stats'
import { Route as AuthLayoutAdminOtaConfigRouteImport } from './routes/_auth/_layout/admin/ota-config'
import { Route as AuthLayoutAdminMqttServerConfigRouteImport } from './routes/_auth/_layout/admin/mqtt-server-config'
import { Route as AuthLayoutAdminMqttConfigRouteImport } from './routes/_auth/_layout/admin/mqtt-config'
import { Route as AuthLayoutAdminMemoryConfigRouteImport } from './routes/_auth/_layout/admin/memory-config'
import { Route as AuthLayoutAdminMcpMarketRouteImport } from './routes/_auth/_layout/admin/mcp-market'
import { Route as AuthLayoutAdminMcpConfigRouteImport } from './routes/_auth/_layout/admin/mcp-config'
import { Route as AuthLayoutAdminLlmConfigRouteImport } from './routes/_auth/_layout/admin/llm-config'
import { Route as AuthLayoutAdminKnowledgeSearchConfigRouteImport } from './routes/_auth/_layout/admin/knowledge-search-config'
import { Route as AuthLayoutAdminGlobalRolesRouteImport } from './routes/_auth/_layout/admin/global-roles'
import { Route as AuthLayoutAdminDevicesRouteImport } from './routes/_auth/_layout/admin/devices'
import { Route as AuthLayoutAdminConfigWizardRouteImport } from './routes/_auth/_layout/admin/config-wizard'
import { Route as AuthLayoutAdminConfigOverviewRouteImport } from './routes/_auth/_layout/admin/config-overview'
import { Route as AuthLayoutAdminChatSettingsRouteImport } from './routes/_auth/_layout/admin/chat-settings'
import { Route as AuthLayoutAdminAsrConfigRouteImport } from './routes/_auth/_layout/admin/asr-config'
import { Route as AuthLayoutAdminAgentsRouteImport } from './routes/_auth/_layout/admin/agents'
import { Route as AuthLayoutAgentsAgentIdHistoryRouteImport } from './routes/_auth/_layout/agents/$agentId/history'
import { Route as AuthLayoutAgentsAgentIdEditRouteImport } from './routes/_auth/_layout/agents/$agentId/edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDocsRoute = OpenapiDocsRouteImport.update({
  id: '/openapi-docs',
  path: '/openapi-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutVoiceClonesRoute = AuthLayoutVoiceClonesRouteImport.update({
  id: '/voice-clones',
  path: '/voice-clones',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSpeakersRoute = AuthLayoutSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutMoreRoute = AuthLayoutMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDashboardRoute = AuthLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAgentsRoute = AuthLayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAgentsIndexRoute = AuthLayoutAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutAgentsRoute,
} as any)
const AuthLayoutUserRolesRoute = AuthLayoutUserRolesRouteImport.update({
  id: '/user/roles',
  path: '/user/roles',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutUserKnowledgeBasesRoute =
  AuthLayoutUserKnowledgeBasesRouteImport.update({
    id: '/user/knowledge-bases',
    path: '/user/knowledge-bases',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutUserDevicesRoute = AuthLayoutUserDevicesRouteImport.update({
  id: '/user/devices',
  path: '/user/devices',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutUserApiTokensRoute = AuthLayoutUserApiTokensRouteImport.update({
  id: '/user/api-tokens',
  path: '/user/api-tokens',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminVisionConfigRoute =
  AuthLayoutAdminVisionConfigRouteImport.update({
    id: '/admin/vision-config',
    path: '/admin/vision-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminVadConfigRoute =
  AuthLayoutAdminVadConfigRouteImport.update({
    id: '/admin/vad-config',
    path: '/admin/vad-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminUsersRoute = AuthLayoutAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminUdpConfigRoute =
  AuthLayoutAdminUdpConfigRouteImport.update({
    id: '/admin/udp-config',
    path: '/admin/udp-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminTtsConfigRoute =
  AuthLayoutAdminTtsConfigRouteImport.update({
    id: '/admin/tts-config',
    path: '/admin/tts-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminSpeakerConfigRoute =
  AuthLayoutAdminSpeakerConfigRouteImport.update({
    id: '/admin/speaker-config',
    path: '/admin/speaker-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminPoolStatsRoute =
  AuthLayoutAdminPoolStatsRouteImport.update({
    id: '/admin/pool-stats',
    path: '/admin/pool-stats',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminOtaConfigRoute =
  AuthLayoutAdminOtaConfigRouteImport.update({
    id: '/admin/ota-config',
    path: '/admin/ota-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminMqttServerConfigRoute =
  AuthLayoutAdminMqttServerConfigRouteImport.update({
    id: '/admin/mqtt-server-config',
    path: '/admin/mqtt-server-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminMqttConfigRoute =
  AuthLayoutAdminMqttConfigRouteImport.update({
    id: '/admin/mqtt-config',
    path: '/admin/mqtt-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminMemoryConfigRoute =
  AuthLayoutAdminMemoryConfigRouteImport.update({
    id: '/admin/memory-config',
    path: '/admin/memory-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminMcpMarketRoute =
  AuthLayoutAdminMcpMarketRouteImport.update({
    id: '/admin/mcp-market',
    path: '/admin/mcp-market',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminMcpConfigRoute =
  AuthLayoutAdminMcpConfigRouteImport.update({
    id: '/admin/mcp-config',
    path: '/admin/mcp-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminLlmConfigRoute =
  AuthLayoutAdminLlmConfigRouteImport.update({
    id: '/admin/llm-config',
    path: '/admin/llm-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminKnowledgeSearchConfigRoute =
  AuthLayoutAdminKnowledgeSearchConfigRouteImport.update({
    id: '/admin/knowledge-search-config',
    path: '/admin/knowledge-search-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminGlobalRolesRoute =
  AuthLayoutAdminGlobalRolesRouteImport.update({
    id: '/admin/global-roles',
    path: '/admin/global-roles',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminDevicesRoute = AuthLayoutAdminDevicesRouteImport.update({
  id: '/admin/devices',
  path: '/admin/devices',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminConfigWizardRoute =
  AuthLayoutAdminConfigWizardRouteImport.update({
    id: '/admin/config-wizard',
    path: '/admin/config-wizard',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminConfigOverviewRoute =
  AuthLayoutAdminConfigOverviewRouteImport.update({
    id: '/admin/config-overview',
    path: '/admin/config-overview',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminChatSettingsRoute =
  AuthLayoutAdminChatSettingsRouteImport.update({
    id: '/admin/chat-settings',
    path: '/admin/chat-settings',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminAsrConfigRoute =
  AuthLayoutAdminAsrConfigRouteImport.update({
    id: '/admin/asr-config',
    path: '/admin/asr-config',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAdminAgentsRoute = AuthLayoutAdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAgentsAgentIdHistoryRoute =
  AuthLayoutAgentsAgentIdHistoryRouteImport.update({
    id: '/$agentId/history',
    path: '/$agentId/history',
    getParentRoute: () => AuthLayoutAgentsRoute,
  } as any)
const AuthLayoutAgentsAgentIdEditRoute =
  AuthLayoutAgentsAgentIdEditRouteImport.update({
    id: '/$agentId/edit',
    path: '/$agentId/edit',
    getParentRoute: () => AuthLayoutAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/openapi-docs': typeof OpenapiDocsRoute
  '/setup': typeof SetupRoute
  '/agents': typeof AuthLayoutAgentsRouteWithChildren
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/more': typeof AuthLayoutMoreRoute
  '/speakers': typeof AuthLayoutSpeakersRoute
  '/voice-clones': typeof AuthLayoutVoiceClonesRoute
  '/admin/agents': typeof AuthLayoutAdminAgentsRoute
  '/admin/asr-config': typeof AuthLayoutAdminAsrConfigRoute
  '/admin/chat-settings': typeof AuthLayoutAdminChatSettingsRoute
  '/admin/config-overview': typeof AuthLayoutAdminConfigOverviewRoute
  '/admin/config-wizard': typeof AuthLayoutAdminConfigWizardRoute
  '/admin/devices': typeof AuthLayoutAdminDevicesRoute
  '/admin/global-roles': typeof AuthLayoutAdminGlobalRolesRoute
  '/admin/knowledge-search-config': typeof AuthLayoutAdminKnowledgeSearchConfigRoute
  '/admin/llm-config': typeof AuthLayoutAdminLlmConfigRoute
  '/admin/mcp-config': typeof AuthLayoutAdminMcpConfigRoute
  '/admin/mcp-market': typeof AuthLayoutAdminMcpMarketRoute
  '/admin/memory-config': typeof AuthLayoutAdminMemoryConfigRoute
  '/admin/mqtt-config': typeof AuthLayoutAdminMqttConfigRoute
  '/admin/mqtt-server-config': typeof AuthLayoutAdminMqttServerConfigRoute
  '/admin/ota-config': typeof AuthLayoutAdminOtaConfigRoute
  '/admin/pool-stats': typeof AuthLayoutAdminPoolStatsRoute
  '/admin/speaker-config': typeof AuthLayoutAdminSpeakerConfigRoute
  '/admin/tts-config': typeof AuthLayoutAdminTtsConfigRoute
  '/admin/udp-config': typeof AuthLayoutAdminUdpConfigRoute
  '/admin/users': typeof AuthLayoutAdminUsersRoute
  '/admin/vad-config': typeof AuthLayoutAdminVadConfigRoute
  '/admin/vision-config': typeof AuthLayoutAdminVisionConfigRoute
  '/user/api-tokens': typeof AuthLayoutUserApiTokensRoute
  '/user/devices': typeof AuthLayoutUserDevicesRoute
  '/user/knowledge-bases': typeof AuthLayoutUserKnowledgeBasesRoute
  '/user/roles': typeof AuthLayoutUserRolesRoute
  '/agents/': typeof AuthLayoutAgentsIndexRoute
  '/agents/$agentId/edit': typeof AuthLayoutAgentsAgentIdEditRoute
  '/agents/$agentId/history': typeof AuthLayoutAgentsAgentIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/openapi-docs': typeof OpenapiDocsRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/more': typeof AuthLayoutMoreRoute
  '/speakers': typeof AuthLayoutSpeakersRoute
  '/voice-clones': typeof AuthLayoutVoiceClonesRoute
  '/admin/agents': typeof AuthLayoutAdminAgentsRoute
  '/admin/asr-config': typeof AuthLayoutAdminAsrConfigRoute
  '/admin/chat-settings': typeof AuthLayoutAdminChatSettingsRoute
  '/admin/config-overview': typeof AuthLayoutAdminConfigOverviewRoute
  '/admin/config-wizard': typeof AuthLayoutAdminConfigWizardRoute
  '/admin/devices': typeof AuthLayoutAdminDevicesRoute
  '/admin/global-roles': typeof AuthLayoutAdminGlobalRolesRoute
  '/admin/knowledge-search-config': typeof AuthLayoutAdminKnowledgeSearchConfigRoute
  '/admin/llm-config': typeof AuthLayoutAdminLlmConfigRoute
  '/admin/mcp-config': typeof AuthLayoutAdminMcpConfigRoute
  '/admin/mcp-market': typeof AuthLayoutAdminMcpMarketRoute
  '/admin/memory-config': typeof AuthLayoutAdminMemoryConfigRoute
  '/admin/mqtt-config': typeof AuthLayoutAdminMqttConfigRoute
  '/admin/mqtt-server-config': typeof AuthLayoutAdminMqttServerConfigRoute
  '/admin/ota-config': typeof AuthLayoutAdminOtaConfigRoute
  '/admin/pool-stats': typeof AuthLayoutAdminPoolStatsRoute
  '/admin/speaker-config': typeof AuthLayoutAdminSpeakerConfigRoute
  '/admin/tts-config': typeof AuthLayoutAdminTtsConfigRoute
  '/admin/udp-config': typeof AuthLayoutAdminUdpConfigRoute
  '/admin/users': typeof AuthLayoutAdminUsersRoute
  '/admin/vad-config': typeof AuthLayoutAdminVadConfigRoute
  '/admin/vision-config': typeof AuthLayoutAdminVisionConfigRoute
  '/user/api-tokens': typeof AuthLayoutUserApiTokensRoute
  '/user/devices': typeof AuthLayoutUserDevicesRoute
  '/user/knowledge-bases': typeof AuthLayoutUserKnowledgeBasesRoute
  '/user/roles': typeof AuthLayoutUserRolesRoute
  '/agents': typeof AuthLayoutAgentsIndexRoute
  '/agents/$agentId/edit': typeof AuthLayoutAgentsAgentIdEditRoute
  '/agents/$agentId/history': typeof AuthLayoutAgentsAgentIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/openapi-docs': typeof OpenapiDocsRoute
  '/setup': typeof SetupRoute
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/_layout/agents': typeof AuthLayoutAgentsRouteWithChildren
  '/_auth/_layout/dashboard': typeof AuthLayoutDashboardRoute
  '/_auth/_layout/more': typeof AuthLayoutMoreRoute
  '/_auth/_layout/speakers': typeof AuthLayoutSpeakersRoute
  '/_auth/_layout/voice-clones': typeof AuthLayoutVoiceClonesRoute
  '/_auth/_layout/admin/agents': typeof AuthLayoutAdminAgentsRoute
  '/_auth/_layout/admin/asr-config': typeof AuthLayoutAdminAsrConfigRoute
  '/_auth/_layout/admin/chat-settings': typeof AuthLayoutAdminChatSettingsRoute
  '/_auth/_layout/admin/config-overview': typeof AuthLayoutAdminConfigOverviewRoute
  '/_auth/_layout/admin/config-wizard': typeof AuthLayoutAdminConfigWizardRoute
  '/_auth/_layout/admin/devices': typeof AuthLayoutAdminDevicesRoute
  '/_auth/_layout/admin/global-roles': typeof AuthLayoutAdminGlobalRolesRoute
  '/_auth/_layout/admin/knowledge-search-config': typeof AuthLayoutAdminKnowledgeSearchConfigRoute
  '/_auth/_layout/admin/llm-config': typeof AuthLayoutAdminLlmConfigRoute
  '/_auth/_layout/admin/mcp-config': typeof AuthLayoutAdminMcpConfigRoute
  '/_auth/_layout/admin/mcp-market': typeof AuthLayoutAdminMcpMarketRoute
  '/_auth/_layout/admin/memory-config': typeof AuthLayoutAdminMemoryConfigRoute
  '/_auth/_layout/admin/mqtt-config': typeof AuthLayoutAdminMqttConfigRoute
  '/_auth/_layout/admin/mqtt-server-config': typeof AuthLayoutAdminMqttServerConfigRoute
  '/_auth/_layout/admin/ota-config': typeof AuthLayoutAdminOtaConfigRoute
  '/_auth/_layout/admin/pool-stats': typeof AuthLayoutAdminPoolStatsRoute
  '/_auth/_layout/admin/speaker-config': typeof AuthLayoutAdminSpeakerConfigRoute
  '/_auth/_layout/admin/tts-config': typeof AuthLayoutAdminTtsConfigRoute
  '/_auth/_layout/admin/udp-config': typeof AuthLayoutAdminUdpConfigRoute
  '/_auth/_layout/admin/users': typeof AuthLayoutAdminUsersRoute
  '/_auth/_layout/admin/vad-config': typeof AuthLayoutAdminVadConfigRoute
  '/_auth/_layout/admin/vision-config': typeof AuthLayoutAdminVisionConfigRoute
  '/_auth/_layout/user/api-tokens': typeof AuthLayoutUserApiTokensRoute
  '/_auth/_layout/user/devices': typeof AuthLayoutUserDevicesRoute
  '/_auth/_layout/user/knowledge-bases': typeof AuthLayoutUserKnowledgeBasesRoute
  '/_auth/_layout/user/roles': typeof AuthLayoutUserRolesRoute
  '/_auth/_layout/agents/': typeof AuthLayoutAgentsIndexRoute
  '/_auth/_layout/agents/$agentId/edit': typeof AuthLayoutAgentsAgentIdEditRoute
  '/_auth/_layout/agents/$agentId/history': typeof AuthLayoutAgentsAgentIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/openapi-docs'
    | '/setup'
    | '/agents'
    | '/dashboard'
    | '/more'
    | '/speakers'
    | '/voice-clones'
    | '/admin/agents'
    | '/admin/asr-config'
    | '/admin/chat-settings'
    | '/admin/config-overview'
    | '/admin/config-wizard'
    | '/admin/devices'
    | '/admin/global-roles'
    | '/admin/knowledge-search-config'
    | '/admin/llm-config'
    | '/admin/mcp-config'
    | '/admin/mcp-market'
    | '/admin/memory-config'
    | '/admin/mqtt-config'
    | '/admin/mqtt-server-config'
    | '/admin/ota-config'
    | '/admin/pool-stats'
    | '/admin/speaker-config'
    | '/admin/tts-config'
    | '/admin/udp-config'
    | '/admin/users'
    | '/admin/vad-config'
    | '/admin/vision-config'
    | '/user/api-tokens'
    | '/user/devices'
    | '/user/knowledge-bases'
    | '/user/roles'
    | '/agents/'
    | '/agents/$agentId/edit'
    | '/agents/$agentId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/openapi-docs'
    | '/setup'
    | '/dashboard'
    | '/more'
    | '/speakers'
    | '/voice-clones'
    | '/admin/agents'
    | '/admin/asr-config'
    | '/admin/chat-settings'
    | '/admin/config-overview'
    | '/admin/config-wizard'
    | '/admin/devices'
    | '/admin/global-roles'
    | '/admin/knowledge-search-config'
    | '/admin/llm-config'
    | '/admin/mcp-config'
    | '/admin/mcp-market'
    | '/admin/memory-config'
    | '/admin/mqtt-config'
    | '/admin/mqtt-server-config'
    | '/admin/ota-config'
    | '/admin/pool-stats'
    | '/admin/speaker-config'
    | '/admin/tts-config'
    | '/admin/udp-config'
    | '/admin/users'
    | '/admin/vad-config'
    | '/admin/vision-config'
    | '/user/api-tokens'
    | '/user/devices'
    | '/user/knowledge-bases'
    | '/user/roles'
    | '/agents'
    | '/agents/$agentId/edit'
    | '/agents/$agentId/history'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/openapi-docs'
    | '/setup'
    | '/_auth/_layout'
    | '/_auth/_layout/agents'
    | '/_auth/_layout/dashboard'
    | '/_auth/_layout/more'
    | '/_auth/_layout/speakers'
    | '/_auth/_layout/voice-clones'
    | '/_auth/_layout/admin/agents'
    | '/_auth/_layout/admin/asr-config'
    | '/_auth/_layout/admin/chat-settings'
    | '/_auth/_layout/admin/config-overview'
    | '/_auth/_layout/admin/config-wizard'
    | '/_auth/_layout/admin/devices'
    | '/_auth/_layout/admin/global-roles'
    | '/_auth/_layout/admin/knowledge-search-config'
    | '/_auth/_layout/admin/llm-config'
    | '/_auth/_layout/admin/mcp-config'
    | '/_auth/_layout/admin/mcp-market'
    | '/_auth/_layout/admin/memory-config'
    | '/_auth/_layout/admin/mqtt-config'
    | '/_auth/_layout/admin/mqtt-server-config'
    | '/_auth/_layout/admin/ota-config'
    | '/_auth/_layout/admin/pool-stats'
    | '/_auth/_layout/admin/speaker-config'
    | '/_auth/_layout/admin/tts-config'
    | '/_auth/_layout/admin/udp-config'
    | '/_auth/_layout/admin/users'
    | '/_auth/_layout/admin/vad-config'
    | '/_auth/_layout/admin/vision-config'
    | '/_auth/_layout/user/api-tokens'
    | '/_auth/_layout/user/devices'
    | '/_auth/_layout/user/knowledge-bases'
    | '/_auth/_layout/user/roles'
    | '/_auth/_layout/agents/'
    | '/_auth/_layout/agents/$agentId/edit'
    | '/_auth/_layout/agents/$agentId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpenapiDocsRoute: typeof OpenapiDocsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi-docs': {
      id: '/openapi-docs'
      path: '/openapi-docs'
      fullPath: '/openapi-docs'
      preLoaderRoute: typeof OpenapiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout/voice-clones': {
      id: '/_auth/_layout/voice-clones'
      path: '/voice-clones'
      fullPath: '/voice-clones'
      preLoaderRoute: typeof AuthLayoutVoiceClonesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/speakers': {
      id: '/_auth/_layout/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof AuthLayoutSpeakersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/more': {
      id: '/_auth/_layout/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthLayoutMoreRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/dashboard': {
      id: '/_auth/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthLayoutDashboardRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/agents': {
      id: '/_auth/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthLayoutAgentsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/agents/': {
      id: '/_auth/_layout/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthLayoutAgentsIndexRouteImport
      parentRoute: typeof AuthLayoutAgentsRoute
    }
    '/_auth/_layout/user/roles': {
      id: '/_auth/_layout/user/roles'
      path: '/user/roles'
      fullPath: '/user/roles'
      preLoaderRoute: typeof AuthLayoutUserRolesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/user/knowledge-bases': {
      id: '/_auth/_layout/user/knowledge-bases'
      path: '/user/knowledge-bases'
      fullPath: '/user/knowledge-bases'
      preLoaderRoute: typeof AuthLayoutUserKnowledgeBasesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/user/devices': {
      id: '/_auth/_layout/user/devices'
      path: '/user/devices'
      fullPath: '/user/devices'
      preLoaderRoute: typeof AuthLayoutUserDevicesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/user/api-tokens': {
      id: '/_auth/_layout/user/api-tokens'
      path: '/user/api-tokens'
      fullPath: '/user/api-tokens'
      preLoaderRoute: typeof AuthLayoutUserApiTokensRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/vision-config': {
      id: '/_auth/_layout/admin/vision-config'
      path: '/admin/vision-config'
      fullPath: '/admin/vision-config'
      preLoaderRoute: typeof AuthLayoutAdminVisionConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/vad-config': {
      id: '/_auth/_layout/admin/vad-config'
      path: '/admin/vad-config'
      fullPath: '/admin/vad-config'
      preLoaderRoute: typeof AuthLayoutAdminVadConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/users': {
      id: '/_auth/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthLayoutAdminUsersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/udp-config': {
      id: '/_auth/_layout/admin/udp-config'
      path: '/admin/udp-config'
      fullPath: '/admin/udp-config'
      preLoaderRoute: typeof AuthLayoutAdminUdpConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/tts-config': {
      id: '/_auth/_layout/admin/tts-config'
      path: '/admin/tts-config'
      fullPath: '/admin/tts-config'
      preLoaderRoute: typeof AuthLayoutAdminTtsConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/speaker-config': {
      id: '/_auth/_layout/admin/speaker-config'
      path: '/admin/speaker-config'
      fullPath: '/admin/speaker-config'
      preLoaderRoute: typeof AuthLayoutAdminSpeakerConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/pool-stats': {
      id: '/_auth/_layout/admin/pool-stats'
      path: '/admin/pool-stats'
      fullPath: '/admin/pool-stats'
      preLoaderRoute: typeof AuthLayoutAdminPoolStatsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/ota-config': {
      id: '/_auth/_layout/admin/ota-config'
      path: '/admin/ota-config'
      fullPath: '/admin/ota-config'
      preLoaderRoute: typeof AuthLayoutAdminOtaConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/mqtt-server-config': {
      id: '/_auth/_layout/admin/mqtt-server-config'
      path: '/admin/mqtt-server-config'
      fullPath: '/admin/mqtt-server-config'
      preLoaderRoute: typeof AuthLayoutAdminMqttServerConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/mqtt-config': {
      id: '/_auth/_layout/admin/mqtt-config'
      path: '/admin/mqtt-config'
      fullPath: '/admin/mqtt-config'
      preLoaderRoute: typeof AuthLayoutAdminMqttConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/memory-config': {
      id: '/_auth/_layout/admin/memory-config'
      path: '/admin/memory-config'
      fullPath: '/admin/memory-config'
      preLoaderRoute: typeof AuthLayoutAdminMemoryConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/mcp-market': {
      id: '/_auth/_layout/admin/mcp-market'
      path: '/admin/mcp-market'
      fullPath: '/admin/mcp-market'
      preLoaderRoute: typeof AuthLayoutAdminMcpMarketRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/mcp-config': {
      id: '/_auth/_layout/admin/mcp-config'
      path: '/admin/mcp-config'
      fullPath: '/admin/mcp-config'
      preLoaderRoute: typeof AuthLayoutAdminMcpConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/llm-config': {
      id: '/_auth/_layout/admin/llm-config'
      path: '/admin/llm-config'
      fullPath: '/admin/llm-config'
      preLoaderRoute: typeof AuthLayoutAdminLlmConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/knowledge-search-config': {
      id: '/_auth/_layout/admin/knowledge-search-config'
      path: '/admin/knowledge-search-config'
      fullPath: '/admin/knowledge-search-config'
      preLoaderRoute: typeof AuthLayoutAdminKnowledgeSearchConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/global-roles': {
      id: '/_auth/_layout/admin/global-roles'
      path: '/admin/global-roles'
      fullPath: '/admin/global-roles'
      preLoaderRoute: typeof AuthLayoutAdminGlobalRolesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/devices': {
      id: '/_auth/_layout/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthLayoutAdminDevicesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/config-wizard': {
      id: '/_auth/_layout/admin/config-wizard'
      path: '/admin/config-wizard'
      fullPath: '/admin/config-wizard'
      preLoaderRoute: typeof AuthLayoutAdminConfigWizardRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/config-overview': {
      id: '/_auth/_layout/admin/config-overview'
      path: '/admin/config-overview'
      fullPath: '/admin/config-overview'
      preLoaderRoute: typeof AuthLayoutAdminConfigOverviewRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/chat-settings': {
      id: '/_auth/_layout/admin/chat-settings'
      path: '/admin/chat-settings'
      fullPath: '/admin/chat-settings'
      preLoaderRoute: typeof AuthLayoutAdminChatSettingsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/asr-config': {
      id: '/_auth/_layout/admin/asr-config'
      path: '/admin/asr-config'
      fullPath: '/admin/asr-config'
      preLoaderRoute: typeof AuthLayoutAdminAsrConfigRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/admin/agents': {
      id: '/_auth/_layout/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthLayoutAdminAgentsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/agents/$agentId/history': {
      id: '/_auth/_layout/agents/$agentId/history'
      path: '/$agentId/history'
      fullPath: '/agents/$agentId/history'
      preLoaderRoute: typeof AuthLayoutAgentsAgentIdHistoryRouteImport
      parentRoute: typeof AuthLayoutAgentsRoute
    }
    '/_auth/_layout/agents/$agentId/edit': {
      id: '/_auth/_layout/agents/$agentId/edit'
      path: '/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof AuthLayoutAgentsAgentIdEditRouteImport
      parentRoute: typeof AuthLayoutAgentsRoute
    }
  }
}

interface AuthLayoutAgentsRouteChildren {
  AuthLayoutAgentsIndexRoute: typeof AuthLayoutAgentsIndexRoute
  AuthLayoutAgentsAgentIdEditRoute: typeof AuthLayoutAgentsAgentIdEditRoute
  AuthLayoutAgentsAgentIdHistoryRoute: typeof AuthLayoutAgentsAgentIdHistoryRoute
}

const AuthLayoutAgentsRouteChildren: AuthLayoutAgentsRouteChildren = {
  AuthLayoutAgentsIndexRoute: AuthLayoutAgentsIndexRoute,
  AuthLayoutAgentsAgentIdEditRoute: AuthLayoutAgentsAgentIdEditRoute,
  AuthLayoutAgentsAgentIdHistoryRoute: AuthLayoutAgentsAgentIdHistoryRoute,
}

const AuthLayoutAgentsRouteWithChildren =
  AuthLayoutAgentsRoute._addFileChildren(AuthLayoutAgentsRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLayoutAgentsRoute: typeof AuthLayoutAgentsRouteWithChildren
  AuthLayoutDashboardRoute: typeof AuthLayoutDashboardRoute
  AuthLayoutMoreRoute: typeof AuthLayoutMoreRoute
  AuthLayoutSpeakersRoute: typeof AuthLayoutSpeakersRoute
  AuthLayoutVoiceClonesRoute: typeof AuthLayoutVoiceClonesRoute
  AuthLayoutAdminAgentsRoute: typeof AuthLayoutAdminAgentsRoute
  AuthLayoutAdminAsrConfigRoute: typeof AuthLayoutAdminAsrConfigRoute
  AuthLayoutAdminChatSettingsRoute: typeof AuthLayoutAdminChatSettingsRoute
  AuthLayoutAdminConfigOverviewRoute: typeof AuthLayoutAdminConfigOverviewRoute
  AuthLayoutAdminConfigWizardRoute: typeof AuthLayoutAdminConfigWizardRoute
  AuthLayoutAdminDevicesRoute: typeof AuthLayoutAdminDevicesRoute
  AuthLayoutAdminGlobalRolesRoute: typeof AuthLayoutAdminGlobalRolesRoute
  AuthLayoutAdminKnowledgeSearchConfigRoute: typeof AuthLayoutAdminKnowledgeSearchConfigRoute
  AuthLayoutAdminLlmConfigRoute: typeof AuthLayoutAdminLlmConfigRoute
  AuthLayoutAdminMcpConfigRoute: typeof AuthLayoutAdminMcpConfigRoute
  AuthLayoutAdminMcpMarketRoute: typeof AuthLayoutAdminMcpMarketRoute
  AuthLayoutAdminMemoryConfigRoute: typeof AuthLayoutAdminMemoryConfigRoute
  AuthLayoutAdminMqttConfigRoute: typeof AuthLayoutAdminMqttConfigRoute
  AuthLayoutAdminMqttServerConfigRoute: typeof AuthLayoutAdminMqttServerConfigRoute
  AuthLayoutAdminOtaConfigRoute: typeof AuthLayoutAdminOtaConfigRoute
  AuthLayoutAdminPoolStatsRoute: typeof AuthLayoutAdminPoolStatsRoute
  AuthLayoutAdminSpeakerConfigRoute: typeof AuthLayoutAdminSpeakerConfigRoute
  AuthLayoutAdminTtsConfigRoute: typeof AuthLayoutAdminTtsConfigRoute
  AuthLayoutAdminUdpConfigRoute: typeof AuthLayoutAdminUdpConfigRoute
  AuthLayoutAdminUsersRoute: typeof AuthLayoutAdminUsersRoute
  AuthLayoutAdminVadConfigRoute: typeof AuthLayoutAdminVadConfigRoute
  AuthLayoutAdminVisionConfigRoute: typeof AuthLayoutAdminVisionConfigRoute
  AuthLayoutUserApiTokensRoute: typeof AuthLayoutUserApiTokensRoute
  AuthLayoutUserDevicesRoute: typeof AuthLayoutUserDevicesRoute
  AuthLayoutUserKnowledgeBasesRoute: typeof AuthLayoutUserKnowledgeBasesRoute
  AuthLayoutUserRolesRoute: typeof AuthLayoutUserRolesRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAgentsRoute: AuthLayoutAgentsRouteWithChildren,
  AuthLayoutDashboardRoute: AuthLayoutDashboardRoute,
  AuthLayoutMoreRoute: AuthLayoutMoreRoute,
  AuthLayoutSpeakersRoute: AuthLayoutSpeakersRoute,
  AuthLayoutVoiceClonesRoute: AuthLayoutVoiceClonesRoute,
  AuthLayoutAdminAgentsRoute: AuthLayoutAdminAgentsRoute,
  AuthLayoutAdminAsrConfigRoute: AuthLayoutAdminAsrConfigRoute,
  AuthLayoutAdminChatSettingsRoute: AuthLayoutAdminChatSettingsRoute,
  AuthLayoutAdminConfigOverviewRoute: AuthLayoutAdminConfigOverviewRoute,
  AuthLayoutAdminConfigWizardRoute: AuthLayoutAdminConfigWizardRoute,
  AuthLayoutAdminDevicesRoute: AuthLayoutAdminDevicesRoute,
  AuthLayoutAdminGlobalRolesRoute: AuthLayoutAdminGlobalRolesRoute,
  AuthLayoutAdminKnowledgeSearchConfigRoute:
    AuthLayoutAdminKnowledgeSearchConfigRoute,
  AuthLayoutAdminLlmConfigRoute: AuthLayoutAdminLlmConfigRoute,
  AuthLayoutAdminMcpConfigRoute: AuthLayoutAdminMcpConfigRoute,
  AuthLayoutAdminMcpMarketRoute: AuthLayoutAdminMcpMarketRoute,
  AuthLayoutAdminMemoryConfigRoute: AuthLayoutAdminMemoryConfigRoute,
  AuthLayoutAdminMqttConfigRoute: AuthLayoutAdminMqttConfigRoute,
  AuthLayoutAdminMqttServerConfigRoute: AuthLayoutAdminMqttServerConfigRoute,
  AuthLayoutAdminOtaConfigRoute: AuthLayoutAdminOtaConfigRoute,
  AuthLayoutAdminPoolStatsRoute: AuthLayoutAdminPoolStatsRoute,
  AuthLayoutAdminSpeakerConfigRoute: AuthLayoutAdminSpeakerConfigRoute,
  AuthLayoutAdminTtsConfigRoute: AuthLayoutAdminTtsConfigRoute,
  AuthLayoutAdminUdpConfigRoute: AuthLayoutAdminUdpConfigRoute,
  AuthLayoutAdminUsersRoute: AuthLayoutAdminUsersRoute,
  AuthLayoutAdminVadConfigRoute: AuthLayoutAdminVadConfigRoute,
  AuthLayoutAdminVisionConfigRoute: AuthLayoutAdminVisionConfigRoute,
  AuthLayoutUserApiTokensRoute: AuthLayoutUserApiTokensRoute,
  AuthLayoutUserDevicesRoute: AuthLayoutUserDevicesRoute,
  AuthLayoutUserKnowledgeBasesRoute: AuthLayoutUserKnowledgeBasesRoute,
  AuthLayoutUserRolesRoute: AuthLayoutUserRolesRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  OpenapiDocsRoute: OpenapiDocsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
