export function getPageTitle(pathname: string, isAdmin: boolean, t: (k: string) => string): string {
  if (pathname.startsWith('/dashboard')) return t('dashboard')
  if (pathname.startsWith('/agents')) return t('my_agents')
  if (pathname.startsWith('/admin/users')) return t('user_management')
  if (pathname.startsWith('/admin/devices')) return t('device_management')
  if (pathname.startsWith('/admin/agents')) return t('agent_management')
  if (pathname.startsWith('/admin/config-overview')) return t('config_overview')
  if (pathname.startsWith('/admin/config-wizard')) return t('config_wizard')
  if (pathname.startsWith('/admin/asr-config')) return t('asr_config')
  if (pathname.startsWith('/admin/llm-config')) return t('llm_config')
  if (pathname.startsWith('/admin/tts-config')) return t('tts_config')
  if (pathname.startsWith('/admin/vad-config')) return t('vad_config')
  if (pathname.startsWith('/admin/mcp-config')) return t('mcp_config')
  if (pathname.startsWith('/admin/global-roles')) return t('global_roles')
  if (pathname.startsWith('/admin/pool-stats')) return t('resource_pool_stats')
  if (pathname.startsWith('/user/devices')) return t('device_list')
  if (pathname.startsWith('/speakers')) return t('voiceprint_management')
  if (pathname.startsWith('/voice-clones')) return t('voice_clone')
  if (pathname.startsWith('/more')) return t('more')
  return isAdmin ? t('dashboard') : t('my_agents')
}
